# -*- coding: utf-8 -*-
# 飯店介紹頁。key 對應 build_guide.HOTEL_Q / 每日行程的 hotel 名稱。
from content_places import S, GMAP

HOTELS = {}

def H(hid, **kw):
    kw["id"] = hid
    HOTELS[hid] = kw

H("h-intercon", key="InterContinental Vienna", zh="維也納洲際飯店", en="InterContinental Wien",
  city="維也納", stay="10/12–10/13・兩晚", day=2, badges=["五星"],
  links=[("Google 地圖", GMAP("InterContinental Wien, Johannesgasse 28, 1037 Wien")),
         ("官方網站", "https://www.vienna.intercontinental.com/")],
  lede="緊鄰市立公園的五星飯店，很多房間面向公園。走路就能到音樂協會、聖史蒂芬大教堂和環城大道。",
  sections=[
    S("基本資訊",
      ("地址", "Johannesgasse 28, 1030 Wien"),
      ("電話", "+43 1 711220"),
      ("規模", "共 392 間客房與套房，從 25 平方公尺的 Classic 房到 140 平方公尺的總統套房。")),
    S("飯店設施",
      ("Café Vienna", "飯店裡的維也納式咖啡館，供應咖啡、維也納甜點和輕食。"),
      ("Intermezzo Bar", "以雞尾酒和長飲聞名的酒吧，聽完音樂會可以回來喝一杯。"),
      ("健身中心", "24 小時開放，房客免費使用。訂房網站資料顯示另有三溫暖和蒸氣室。"),
      ("客房備品", "空調、保險箱、迷你吧、泡茶咖啡設備、浴袍、拖鞋和吹風機，還有枕頭選單可以挑枕頭。"),
      ("Club InterContinental", "11–12 樓的行政酒廊，限套房與指定房型使用。"),
      ("其他服務", "24 小時客房服務、禮賓服務、商務中心。")),
    S("周邊步行",
      ("市立公園 Stadtpark", "就在飯店前面。金色小約翰・史特勞斯雕像和 Kursalon 音樂廳都在公園裡。"),
      ("[[p-concert|音樂協會布拉姆斯廳]]", "約 10 分鐘。"),
      ("[[p-stephansdom|聖史蒂芬大教堂]]", "約 15 分鐘。"),
      ("地鐵", "公園旁就是地鐵 U4 的 Stadtpark 站。")),
    S("小知識",
      "飯店旁 Heumarkt 一帶有一項包含高樓的改建計畫，因為可能破壞老城天際線，2017 年讓「維也納歷史中心」被聯合國教科文組織列入瀕危世界遺產名單。"),
  ])

H("h-roessl", key="Romantik Hotel Im Weissen Rössl", zh="傳奇白馬飯店", en="Romantik Hotel Im Weissen Rössl am Wolfgangsee",
  city="聖沃夫岡", stay="10/14–10/15・兩晚", day=4, badges=["四星 Superior"],
  links=[("Google 地圖", GMAP("Romantik Hotel Im Weissen Rössl, St. Wolfgang im Salzkammergut")),
         ("官方網站", "https://www.weissesroessl.at/en/")],
  lede="直接蓋在沃夫岡湖岸上的老牌飯店，因輕歌劇《白馬酒店》聞名。大部分房間看得到湖，泡在湖上的溫水泳池裡看山，是這裡最有名的體驗。",
  sections=[
    S("基本資訊",
      ("地址", "Markt 74, 5360 St. Wolfgang im Salzkammergut"),
      ("電話", "+43 6138 2306"),
      ("經營", "由 Peter 家族經營，屬於歐洲 Romantik Hotels 聯盟。")),
    S("建在湖上的 SPA",
      ("湖上溫水泳池", "全年加熱到約 30°C，泳池就浮在湖面上。"),
      ("Rössl Pool", "恆溫 37°C 的熱水池。"),
      ("其他", "漂浮按摩池、蒸氣室、湖景三溫暖、健身房、全景休息室和日光露台，整個 SPA 約 1,500 平方公尺。")),
    S("餐廳與酒吧",
      ("Seerestaurant 湖畔餐廳", "以湖區魚料理和奧地利傳統菜為主，坐在湖邊吃飯。"),
      ("Poll's Kaiserterrasse", "飯店的精緻餐廳，2023 年獲 Gault & Millau 三頂廚師帽。"),
      ("Rock Cellar", "地窖葡萄酒吧。"),
      ("其他", "還有 Rösslerei、Badstüberl 和 Fishing Lodge 幾間小餐館。")),
    S("活動",
      "飯店提供腳踏船和電動船，可以自己划到湖上。湖邊就有遊船碼頭（季節性營運），可以搭船到對岸的聖吉爾根。",
      "飯店的故事與白馬酒店輕歌劇，請看[[p-stwolfgang|聖沃夫岡]]頁。"),
    S("住宿小提醒",
      "記得帶泳衣。10 月湖邊早晚氣溫低，泡完湯要趕快擦乾保暖。連泊兩晚，第二天不用整理大行李。"),
  ])

H("h-andel", key="Hotel Zlatý Anděl", zh="金色天使飯店", en="Hotel Zlatý Anděl",
  city="庫倫洛夫", stay="10/16・一晚", day=6, badges=[],
  links=[("Google 地圖", GMAP("Hotel Zlatý Anděl, Náměstí Svornosti, Český Krumlov")),
         ("官方網站", "https://www.hotelzlatyandel.cz/")],
  lede="就在庫倫洛夫主廣場 Svornosti 廣場上，原本是一棟哥德式老房子。出門就是老城中心，清晨和晚上可以在幾乎沒有遊客的廣場上散步。",
  sections=[
    S("基本資訊",
      ("地址", "náměstí Svornosti 11, 381 01 Český Krumlov"),
      ("電話", "+420 380 712 310"),
      ("房間", "約 46 間客房，另有幾間公寓式套房，浴室空間寬敞。")),
    S("飯店設施",
      ("Petr Vok 餐廳", "木樑裝潢的傳統餐廳，供應波希米亞菜和國際料理。"),
      ("Don Julius 餐廳", "另一間傳統風格的餐廳。"),
      ("咖啡館與露台", "供應自製甜點，可以坐在廣場邊。"),
      ("酒吧", "有音樂的雞尾酒吧。"),
      ("其他", "換匯服務、車庫與私人停車位。")),
    S("餐廳名字的故事",
      ("Petr Vok", "玫瑰家族最後一位當家人（1539–1611）。他因為債務，在 1602 年把庫倫洛夫賣給皇帝魯道夫二世，過世後家族就此絕嗣。"),
      ("Don Julius", "魯道夫二世的私生子。他精神失常，被父親安置在庫倫洛夫城堡，1608 年殺害了一位澡堂老闆的女兒，之後被軟禁，1609 年死在城堡裡。這是庫倫洛夫最有名的黑暗傳說。")),
    S("住宿小提醒",
      "老城區限制車輛進入，巴士會停在老城外；這個行程有大行李送到房間的服務。領隊建議每間房把當晚要用的東西集中成一件大行李箱，或準備一晚的過夜包，減少搬行李的時間。飯店就在廣場上，晚餐後可以再出門看夜景。小鎮的更多故事請看[[p-krumlov|庫倫洛夫]]頁。"),
  ])

H("h-rubezahl", key="Luxury Historical Castle Hotel & Golf", zh="魯伯薩爾城堡飯店", en="Rübezahl Marienbad Luxury Historical Castle Hotel & Golf",
  city="瑪麗安斯凱", stay="10/17・一晚", day=7, badges=[],
  links=[("Google 地圖", GMAP("Rubezahl Marienbad Luxury Historical Castle Hotel & Golf, Mariánské Lázně")),
         ("官方網站", "https://www.castlehotelcollection.com/rubezahl-castle/")],
  lede="1903 年完成的城堡式建築，位在瑪麗安斯凱溫泉區外圍的森林邊。2015 年整修後重新開幕，新增了羅馬浴場風格的 SPA。",
  sections=[
    S("基本資訊",
      ("建築", "1903 年完成，由維也納建築師阿諾德・海曼設計。名字取自德捷邊境巨人山脈的山精傳說「魯伯薩爾」。"),
      ("房間", "41 間客房與套房，浴室使用大理石和縞瑪瑙，附按摩淋浴。"),
      ("高爾夫", "約 1 公里外就是 1905 年開幕的瑪麗安斯凱皇家高爾夫俱樂部。")),
    S("SPA 與健康",
      ("羅馬愛爾蘭浴", "依序使用土耳其浴、三溫暖、濕式按摩和按摩池的療程。"),
      ("其他", "泳池、健身房，以及按摩、美容和排毒療程。")),
    S("餐廳與酒吧",
      ("Castle Restaurant", "城堡主餐廳。這晚的晚餐是「飯店內主廚晚餐」。"),
      ("Café Bar 與 Wine Cellar", "咖啡吧和地窖酒窖。"),
      ("城堡沙龍", "可以在廳裡玩橋牌、抽雪茄，延續老派溫泉療養地的生活方式。")),
    S("住宿小提醒",
      "飯店在城郊，晚上外面很暗，附近也沒什麼店，晚餐後很適合留在飯店使用 SPA。療程建議抵達後先向櫃檯預約。溫泉小鎮的故事請看[[p-marienbad|瑪麗安斯凱]]頁。"),
  ])

H("h-kingscourt", key="Hotel KINGS COURT Prague", zh="布拉格國王宮廷飯店", en="Hotel KINGS COURT",
  city="布拉格", stay="10/18–10/20・三晚", day=8, badges=["五星"],
  links=[("Google 地圖", GMAP("Hotel KINGS COURT, U Obecního domu 3, Praha 1")),
         ("官方網站", "https://www.hotelkingscourt.cz/")],
  lede="共和廣場旁一棟新文藝復興風格宮殿裡的五星飯店，隔壁是新藝術風格的市民會館和火藥塔。布拉格三晚都住這裡，走路就能到舊城廣場。",
  sections=[
    S("基本資訊",
      ("地址", "U Obecního domu 3, 110 00 Praha 1"),
      ("電話", "+420 224 222 888"),
      ("交通", "飯店在共和廣場 Náměstí Republiky，地鐵 B 線同名車站就在旁邊。")),
    S("餐廳與酒廊",
      ("ADELE Restaurant & Bar", "以義大利料理為靈感的餐廳，面對共和廣場，全年有露台座位。"),
      ("MAJESTY Lounge", "飯店的酒廊空間。"),
      ("Executive Lounge", "限行政客房與套房房客，提供點心。")),
    S("SPA 與健身",
      ("SPA", "放鬆泳池（需穿泳衣）、三溫暖（需用浴巾包覆）、按摩與美容療程。"),
      ("開放時間", "SPA 每天 10:00–22:00，按摩 09:00–21:30，健身房 24 小時開放。"),
      ("費用", "行政客房與套房房客免費；Deluxe 房房客每人每日 350 克朗（官網公告）。使用前可以先問櫃檯你們的房型。"),
      ("兒童", "12 歲以下要由大人陪同，限 10:00–16:00 使用。")),
    S("周邊步行",
      ("市民會館 Obecní dům", "就在隔壁，是布拉格新藝術建築的代表，慕夏負責了市長廳的裝飾。"),
      ("火藥塔", "舊城的哥德式城門，穿過去就進入舊城。"),
      ("[[p-oldtownsq|舊城廣場]]", "約 10 分鐘。"),
      ("[[p-imperial|帝國咖啡館]]", "約 5 分鐘。"),
      ("[[p-parizska|巴黎街 Celine]]", "約 12 分鐘。")),
    S("住宿小提醒",
      "三晚連泊，不用每天整理大行李。最後一天是早班機，前一晚就把行李整理好。"),
  ])

H("h-imperial", kind="venue", key="Café Imperial", zh="帝國咖啡館", en="Café Imperial",
  city="布拉格", day=10, badges=["10/20 18:00・6 位已訂位", "米其林指南 2026"],
  links=[("Google 地圖", GMAP("Café Imperial, Na Poříčí 15, Praha 1")),
         ("官方網站", "https://www.cafeimperial.cz/en/homepage/"),
         ("訂位／改期", "https://cafeimperial.cz/en/reservation/"),
         ("單點菜單", "https://www.cafeimperial.cz/en/a-la-carte/")],
  lede="位在裝飾藝術風格的 Imperial Hotel 一樓，1914 年開業至今。牆面鋪滿獨特的陶瓷磚，天花板是原始的馬賽克。主廚兼老闆是捷克名廚波爾萊希。",
  sections=[
    S("基本資訊",
      ("地址", "Na Poříčí 15, Praha 1"),
      ("電話", "+420 246 011 440"),
      ("營業時間", "每天 07:00–23:00"),
      ("服裝", "整潔休閒即可（smart casual）。"),
      ("付款", "可以刷信用卡。"),
      ("其他", "歡迎兒童；寵物只限導盲犬。另有包廂可預約。")),
    S("用餐時段",
      ("早餐", "每天 07:00 起，有自助式和單點。"),
      ("午餐", "有每日午間特餐。"),
      ("下午茶", "14:30–16:45 可以訂位。"),
      ("晚餐", "17:00–23:00 只接受晚餐訂位，要點餐，不能只點咖啡。")),
    S("你的訂位",
      ("時間", "10/20（二）18:00，6 位。"),
      ("改期或取消", "請用官網的訂位頁處理。"),
      ("客滿時的備案", "官網建議旁邊約 15 公尺的姊妹餐廳 Next Door。"),
      ("怎麼去", "從 Hotel KINGS COURT 往東走約 5 分鐘。")),
    S("菜單參考",
      "以下是官網單點菜單的價格（含稅，克朗），實際以現場菜單為準。",
      ("奶油醬燉牛肉配饅頭片、蔓越莓", "398 CZK"),
      ("油封鴨配紫甘藍、馬鈴薯餃", "477 CZK"),
      ("小牛肉炸排配馬鈴薯泥", "499 CZK"),
      ("燉羊膝配馬鬱蘭、奶油菠菜", "479 CZK"),
      ("牛菲力韃靼配酸豆、紅蔥頭、第戎芥末", "397 CZK"),
      ("威靈頓牛排配紅酒醬", "699 CZK"),
      ("甜點", "另有甜點菜單，蛋糕每天現做。")),
    S("小提醒",
      "捷克餐廳的小費約 10%，結帳時直接告訴店員含小費的總額。咖啡館的歷史、名人故事和推薦菜，請看[[p-imperial|帝國咖啡館]]頁。"),
  ])
